### ISSUE TITLE
Commas in Keyframes

### ISSUE THREAD

**Issue by DmitriyLazarev** [dart-lang/csslib#105]
* Dart SDK Version 2.7.2
* AngularDart Version 6.0.0-alpha and 5.3.1
* macOS

I use less_dart in my project. I create styles.less file and write LESS example code: 
```
@keyframes loadMaskAnimation {
  10%,
  20%,
  30% {
    background-color: yellow;
  }
  50% {
    background-color: black;
  }
}
```
after build and compiling I have next files:
1. styles.css - with normal good result
2. styles.css.dart - final List<dynamic> styles = [':host \n@keyframes loadMaskAnimation {\n  **10%,\n  20%,\n  30%** {\n    background-color: yellow;\n  }\n  50% {\n    background-color: black;\n  }\n}\n'];

As you see, in this step I still have commas between 10%, and 20%. It means, that less_dart works good.

3. styles.css.shim.dart - problem is here - final List<dynamic> styles = ['._nghost-%ID% @keyframes loadMaskAnimation{**10% 20% 30%**{background-color:yellow}50%{background-color:black}}'];

And now commas is missed and my animation is broken.
Сan I somehow fix this in my project? I hope you will fix it in next versions.

**Comment by leonsenft** [comment]
Angular relies on `pkg:csslib` to parse CSS, so this must be a `pkg:csslib` bug.

**Comment by natebosch** [comment]
I tracked down that this change causes problems because it puts commas in between percent terms in places where they can't exist, like `grid-template-columns: 50%, 50%;` when it should be `grid-template-columns: 50% 50%;`.

I think a full fix would need to be aware of the `@keyframes` context, which implies making the visitor stateful :(

**Comment by zzwx** [comment]
There has to be a solution. It's a little ironic that the parser expects commas, but produces styles that can't itself parse.

So this actually fails to parse (as of #[f746368](https://github.com/dart-lang/csslib/commit/f746368a0a53cf8f68fd71b218239034e88841d5)):
```css
@-webkit-keyframes bounce {
  0% 100% {
  transform: translateY(-25%);
  -webkit-animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
  animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
  }
  50% {
  transform: none;
  -webkit-animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
}
```
