### ISSUE TITLE
Errors when parsing bulma.css

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/csslib#136]
The following repro finds 6 errors in `bulma/css/bulma.css` from:
https://github.com/jgthms/bulma/releases/tag/0.9.3

```dart
import 'dart:io';
import 'package:csslib/parser.dart';

const testOptions = PreprocessorOptions(
  useColors: false,
  checked: false,
  warningsAsErrors: true,
  inputFile: 'memory',
);

void main() {
  final cssFile = File('bulma.css');
  final css = cssFile.readAsStringSync();
  final errors = <Message>[];
  final stylesheet = parse(css, errors: errors, options: testOptions);
  print(
      'parsed ${stylesheet.topLevels.length} nodes with ${errors.length} errors');
}
```

**Comment by devoncarew** [comment]
The first error - which may be causing the others - is on:

```css
.hero.is-white a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current),
                                                                                ^
.hero.is-white strong {
  color: inherit;
}
```

I suspect this is related to https://github.com/dart-lang/csslib/issues/141 and our handling of pseudo selectors (`:not()`). We're (mostly?) following the selector level 3 grammar - we don't the newer support level 4.
