### ISSUE TITLE
Support arithmetic operators inside min, max, and clamp functions

### ISSUE THREAD

**Issue by jathak** [dart-lang/csslib#144]
Code like:

```css
a {
  b: min(16px, var(--foo) + 4px);
}
```

fails to parse, but is equivalent to

```css
a {
  b: min(16px, calc(var(--foo) + 4px));
}
```
which parses fine.
