### ISSUE TITLE
incorrect text spans for declarations containing calc() expression

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/csslib#17]
This:

```css
.foo { height: calc(100% - 55px); }
```

Generates incomplete declaration span:

```
height: calc(
```

See also: https://github.com/dart-lang/csslib/pull/16
