### ISSUE TITLE
Line names in grid-template-columns and grid-template-rows are not parsed

### ISSUE THREAD

**Issue by TastyPi** [dart-lang/csslib#96]
Example:

```css
.example-grid {
  display: grid;
  grid-template-columns: [start] auto [middle] 1fr [end];
  grid-template-rows: [top] auto [middle] 1fr [bottom];
}
```

Gives the errors:

```
[
    Message:error on line 3, column 26: Expecting a positive number  
    ╷  
  3 │   grid-template-columns: [start] auto [middle] 1fr [end];  
    │                          ^^^^^^  
    ╵,
    Message:error on line 3, column 39: Expecting a positive number  
    ╷  
  3 │   grid-template-columns: [start] auto [middle] 1fr [end];  
    │                                       ^^^^^^^  
    ╵,
    Message:error on line 3, column 52: Expecting a positive number  
    ╷  
  3 │   grid-template-columns: [start] auto [middle] 1fr [end];  
    │                                                    ^^^^  
    ╵,
    Message:error on line 4, column 23: Expecting a positive number  
    ╷  
  4 │   grid-template-rows: [top] auto [middle] 1fr [bottom];  
    │                       ^^^^  
    ╵,
    Message:error on line 4, column 34: Expecting a positive number  
    ╷  
  4 │   grid-template-rows: [top] auto [middle] 1fr [bottom];  
    │                                  ^^^^^^^  
    ╵,
    Message:error on line 4, column 47: Expecting a positive number  
    ╷  
  4 │   grid-template-rows: [top] auto [middle] 1fr [bottom];  
    │                                               ^^^^^^^  
    ╵
]
```
